"use client";
import { useState } from "react";
import { Heart, Image as ImageIcon, MessageCircle, MoreHorizontal, Palette, PawPrint, Send, Sparkles, X } from "lucide-react";
import { AvatarImage } from "./avatar-image";
import type { H1Footprint, SocialActivityState } from "./journey-one-state";

type Props={avatar:number;nickname:string;footprint:H1Footprint;recordFootprint:(field:keyof H1Footprint,value:string|null)=>void;activity:SocialActivityState;setActivity:(value:SocialActivityState|((current:SocialActivityState)=>SocialActivityState))=>void};
type NPCComment={avatar:string;nickname:string;text:string};
type Interaction={type:"quickReply";options:string[]}|{type:"monthPicker"};
type FeedPost={id:string;who:string;avatar:string;time:string;text:string;art:"dream"|"birthday"|"pixel"|"cat"|"club"|"garden";visual:string;likes:number;comments:NPCComment[];commentInteraction:Interaction;schoolShare?:boolean};
const c=(avatar:string,nickname:string,text:string):NPCComment=>({avatar,nickname,text});
const feedPosts:FeedPost[]=[
 {id:"dream",who:"Linh Sao",avatar:"🎨",time:"8 phút",text:"Mình vừa hoàn thành bức tranh thành phố trên mây. Mọi người thích góc nào nhất?",art:"dream",visual:"☁️  🎨  🌇",likes:24,comments:[c("🌟","Sao Nhỏ","Màu trời đẹp quá!"),c("🌈","Lá Xanh","Tớ thích tòa nhà có vườn cây 🌿")],commentInteraction:{type:"quickReply",options:["Mình thích tòa nhà trên mây ☁️","Màu sắc đẹp quá 🎨","Góc cây xanh dễ thương 🌱"]}},
 {id:"birthday",who:"Mây Cam",avatar:"🍊",time:"16 phút",text:"Tháng sinh của mình là tháng 6 ☀️ Có ai cùng tháng không? Team cùng tháng điểm danh nào! 🎂",art:"birthday",visual:"🎈  6  🎂",likes:32,comments:[c("🌱","Bắp","Tháng 3 nè 🌱"),c("🍄","Nấm","Mình tháng 11!"),c("☁️","Sóc Mây","Team tháng 6 🙌")],commentInteraction:{type:"monthPicker"}},
 {id:"pixel",who:"Nam Byte",avatar:"👾",time:"25 phút",text:"Pixel Quest tối nay có cổng bí mật mới! Ai lập đội cùng mình không?",art:"pixel",visual:"💎  👾  ⭐",likes:18,comments:[c("🚀","Tí Sao","Cho tớ một chỗ nhé!"),c("✨","Mây Tím","Hẹn gặp ở cổng sao ✨")],commentInteraction:{type:"quickReply",options:["Cho mình vào đội với! 🎮","Mình sẽ khám phá sau 👀","Cổng bí mật nghe thú vị quá!"]}},
 {id:"cat",who:"Bông Kem",avatar:"🐱",time:"1 giờ",text:"Sinh nhật Mochi tròn 2 tuổi 🎂 Hôm nay bạn ấy được ăn bánh cá ngừ!",art:"cat",visual:"🐱  🎂  🐟",likes:31,comments:[c("🐾","Mèo Mun","Chúc Mochi tuổi mới thật vui!"),c("😸","Bơ","Chiếc mũ xinh ghê 😸")],commentInteraction:{type:"quickReply",options:["Chúc Mochi sinh nhật vui vẻ! 🎂","Mochi dễ thương quá 🐾","Cho Mochi một trái tim ❤️"]}},
 {id:"club",who:"Câu lạc bộ Mây",avatar:"📷",time:"2 giờ",text:"Góc sáng tạo hôm nay 📷 Bạn đang làm gì thú vị? Chia sẻ một khoảnh khắc với cộng đồng nhé!",art:"club",visual:"✂️  🖍️  📐",likes:27,comments:[c("📄","Gấu Giấy","Tớ đang làm mô hình giấy!"),c("💌","Nắng","Mình vừa vẽ xong một tấm thiệp.")],commentInteraction:{type:"quickReply",options:["Ngày hội trông vui quá! 🎨","Mình thích góc sáng tạo này!","Có nhiều hoạt động hay ghê!"]},schoolShare:true},
 {id:"garden",who:"Minh Lá",avatar:"🌿",time:"3 giờ",text:"Mầm cây nhỏ ở ban công đã có chiếc lá thứ tư rồi. Cuối tuần mình sẽ vẽ lại từng giai đoạn!",art:"garden",visual:"🌱  🪴  ☀️",likes:21,comments:[c("🌼","Cúc Nhỏ","Nhớ chia sẻ bức vẽ nhé!"),c("🌳","Lá Xanh","Cây lớn nhanh thật đó 🌿")],commentInteraction:{type:"quickReply",options:["Chiếc lá mới xinh quá 🌱","Mình cũng thích trồng cây!","Mong xem bức vẽ của bạn 🎨"]}}
];

type Exposure="school"|"class"|"schedule"|"homeAddress"|"phone";
type Moment={id:string;title:string;description:string;alt:string;visual:string;detail:string;exposures:Exposure[]};
const galleryOptions:Moment[]=[
 {id:"desk",title:"Góc màu sắc",description:"Bàn vẽ và hộp màu",alt:"Góc bàn vẽ với giấy, bút chì, hộp màu và giấy vẽ",visual:"✏️  🎨  📒",detail:"",exposures:[]},
 {id:"festival",title:"Ngày hội sáng tạo",description:"Sân trường trong ngày hội",alt:"Sân trường mô phỏng trong ngày hội, phía sau có biển TRƯỜNG MÂY XANH",visual:"🎪  🏫  🎨",detail:"TRƯỜNG MÂY XANH",exposures:["school"]},
 {id:"model",title:"Mô hình tí hon",description:"Thành phố giấy thủ công",alt:"Mô hình thành phố, nhà cây và đồ thủ công",visual:"🏠  🌳  🏢",detail:"",exposures:[]},
 {id:"snack",title:"Bữa xế vui vẻ",description:"Bánh, sữa và truyện tranh",alt:"Bàn ăn nhỏ có bánh, hộp sữa và sách truyện",visual:"🧁  🥛  📚",detail:"",exposures:[]},
 {id:"playground",title:"Giờ ra chơi",description:"Một chiều trên sân bóng",alt:"Sân chơi mô phỏng với phù hiệu MÂY XANH nhỏ trên áo",visual:"⚽  🛝  🧢",detail:"MÂY XANH",exposures:["school"]},
 {id:"study",title:"Góc học tập",description:"Sách vở và thời khóa biểu",alt:"Bàn học có giấy thời khóa biểu ghi LỚP 5A và TRƯỜNG MÂY XANH",visual:"📚  ✏️  📅",detail:"LỚP 5A · TRƯỜNG MÂY XANH · TKB",exposures:["class","school","schedule"]},
 {id:"parcel",title:"Món đồ vừa nhận",description:"Hộp hàng và cuốn sách mới",alt:"Bưu kiện mô phỏng có nhãn 12 Đường Mây Trắng, Khu Cầu Vồng",visual:"📦  📖  ✨",detail:"12 Đường Mây Trắng · Khu Cầu Vồng",exposures:["homeAddress"]},
 {id:"my-desk",title:"Góc bàn của mình",description:"Cốc bút và giấy ghi chú",alt:"Góc bàn có thẻ liên hệ mô phỏng ghi 09xx xxx xxx",visual:"🖊️  🗒️  ☕",detail:"09xx xxx xxx",exposures:["phone"]},
 {id:"morning",title:"Chuẩn bị ngày mới",description:"Balô và đồ dùng học tập",alt:"Balô có thẻ mô phỏng ghi LỚP 5A và MÂY XANH",visual:"🎒  🧃  🖍️",detail:"LỚP 5A · MÂY XANH",exposures:["class","school"]}
];
const ownReplies=["Khoảnh khắc này thật vui ✨","Cảm ơn mọi người nhé!","Mình cũng rất thích tấm này 💙"];

export function SocialZone({avatar,nickname,footprint,recordFootprint,activity,setActivity}:Props){
 const[open,setOpen]=useState<string[]>([]),[monthOpen,setMonthOpen]=useState(false),[galleryOpen,setGalleryOpen]=useState(false);
 const[selected,setSelected]=useState<string|null>(null);
 const liked=activity.reactions,shared=activity.shares;
 const replies=Object.fromEntries(activity.comments.map(comment=>[comment.postId,comment.value]));
 const currentMonth=footprint.birthMonth?.match(/\d{1,2}/)?.[0]??null;
 const trends=[{Icon:Palette,name:"#GócSángTạo",meta:"38 bài mới"},{Icon:Sparkles,name:"#PixelQuest",meta:"24 người tham gia"},{Icon:PawPrint,name:"#BạnThúCưng",meta:"17 ảnh mới"}];
 const toggleActivity=(field:"reactions"|"shares",id:string)=>setActivity(current=>({...current,[field]:current[field].includes(id)?current[field].filter(x=>x!==id):[...current[field],id]}));
 const show=(id:string)=>setOpen(items=>items.includes(id)?items:[...items,id]);
 const reply=(postId:string,value:string)=>{setActivity(current=>{const createdAt=Math.max(0,...current.posts.map(post=>post.createdAt),...current.comments.map(comment=>comment.createdAt))+1;return{...current,comments:[...current.comments.filter(comment=>comment.postId!==postId),{id:`comment-${createdAt}-${postId}`,postId,value,createdAt}]}});show(postId)};
 const comment=(post:FeedPost)=>{show(post.id);if(post.commentInteraction.type==="monthPicker")setMonthOpen(true)};
 const chooseMonth=(month:number)=>{recordFootprint("birthMonth",String(month));reply("birthday",`Mình tháng ${month}! 🎂`);setMonthOpen(false)};
 const publish=()=>{const moment=galleryOptions.find(x=>x.id===selected);if(!moment)return;setActivity(current=>{const createdAt=Math.max(0,...current.posts.map(post=>post.createdAt),...current.comments.map(comment=>comment.createdAt))+1;return{...current,posts:[{id:`post-${createdAt}-${moment.id}`,momentId:moment.id,caption:"Một khoảnh khắc hôm nay ✨",createdAt,exposures:[...moment.exposures]},...current.posts]}});if(moment.exposures.includes("school"))recordFootprint("school","Trường Mây Xanh");setGalleryOpen(false);setSelected(null)};
 const playerComment=(id:string)=>replies[id]&&<p className="player-comment"><AvatarImage index={avatar}/><span><b>{nickname}</b>{replies[id]}</span></p>;
 const actions=(id:string,likes:number,onComment:()=>void)=><footer><button type="button" className={liked.includes(id)?"liked":""} onClick={()=>toggleActivity("reactions",id)} aria-pressed={liked.includes(id)}><Heart/>{likes+(liked.includes(id)?1:0)}</button><button type="button" onClick={onComment} aria-expanded={open.includes(id)}><MessageCircle/> Bình luận</button><button type="button" className={shared.includes(id)?"shared":""} onClick={()=>toggleActivity("shares",id)} aria-pressed={shared.includes(id)}><Send/> {shared.includes(id)?"Đã chia sẻ":"Chia sẻ"}</button></footer>;
 return <>
  <div className="social-layout"><section className="feed" aria-label="Bảng tin Social Zone">
   <div className="composer"><AvatarImage index={avatar}/><button type="button" onClick={()=>setGalleryOpen(true)}><span>{nickname}</span> đang nghĩ gì?</button><button type="button" className="composer-media" onClick={()=>setGalleryOpen(true)} aria-label="Chia sẻ khoảnh khắc mô phỏng"><ImageIcon/></button></div>
   {activity.posts.map(post=>{const moment=galleryOptions.find(option=>option.id===post.momentId);if(!moment)return null;return <article className="post social-post player-post" key={post.id} data-exposures={post.exposures.join(",")}><header><AvatarImage index={avatar}/><div><b>{nickname}</b><small>Đã đăng · Social Zone</small></div><button type="button" className="post-more" aria-label="Tùy chọn bài viết của bạn"><MoreHorizontal/></button></header><p>{post.caption}</p><div className={`gallery-scene gallery-${moment.id}`} role="img" aria-label={moment.alt}>{moment.detail&&<span className="scene-detail" aria-hidden="true">{moment.detail}</span>}<span className="scene-visual" aria-hidden="true">{moment.visual}</span></div>{actions(post.id,0,()=>show(post.id))}{open.includes(post.id)&&<div className="post-comments"><div className="quick-replies" aria-label="Bình luận nhanh">{ownReplies.map(x=><button type="button" key={x} className={replies[post.id]===x?"selected":""} onClick={()=>reply(post.id,x)}>{x}</button>)}</div>{playerComment(post.id)}</div>}</article>})}
   {feedPosts.map(post=><article className={`post social-post social-post-${post.art}`} key={post.id}><header><span className="npc-avatar" aria-hidden="true">{post.avatar}</span><div><b>{post.who}</b><small>{post.time} trước · Social Zone</small></div><button type="button" className="post-more" aria-label={`Tùy chọn bài viết của ${post.who}`}><MoreHorizontal/></button></header><p>{post.text}</p><div className={`post-art ${post.art}`} role="img" aria-label={`Minh họa cho bài viết của ${post.who}`}><span>{post.visual}</span></div>{post.schoolShare&&<button type="button" className="share-moment" onClick={()=>setGalleryOpen(true)}><ImageIcon/> Chia sẻ khoảnh khắc</button>}{actions(post.id,post.likes,()=>comment(post))}{open.includes(post.id)&&<div className="post-comments">{post.comments.map(x=><p key={`${x.nickname}-${x.text}`}><span aria-hidden="true">{x.avatar}</span><span><b>{x.nickname}</b>{x.text}</span></p>)}{post.commentInteraction.type==="quickReply"&&<div className="quick-replies" aria-label="Bình luận nhanh">{post.commentInteraction.options.map(x=><button type="button" key={x} className={replies[post.id]===x?"selected":""} onClick={()=>reply(post.id,x)}>{x}</button>)}</div>}{post.commentInteraction.type==="monthPicker"&&<button type="button" className="choose-month-comment" onClick={()=>setMonthOpen(true)}>{currentMonth?"Đổi tháng trong bình luận":"Viết bình luận theo tháng"}</button>}{playerComment(post.id)}</div>}</article>)}
  </section><aside className="social-side" aria-label="Đang được quan tâm"><b>Đang được quan tâm</b>{trends.map(({Icon,name,meta})=><div key={name}><Icon/><p><strong>{name}</strong><small>{meta}</small></p></div>)}</aside></div>
  {monthOpen&&<div className="social-modal" role="dialog" aria-modal="true" aria-labelledby="month-picker-title" onMouseDown={e=>{if(e.target===e.currentTarget)setMonthOpen(false)}}><section className="month-picker"><header><div><small>BÌNH LUẬN GIẢ LẬP</small><h2 id="month-picker-title">Bạn muốn bình luận tháng nào?</h2></div><button type="button" onClick={()=>setMonthOpen(false)} aria-label="Đóng chọn tháng"><X/></button></header><p>Chọn một câu bình luận có sẵn để tham gia cuộc trò chuyện.</p><div className="month-grid">{Array.from({length:12},(_,i)=>i+1).map(month=><button type="button" key={month} className={currentMonth===String(month)?"selected":""} onClick={()=>chooseMonth(month)} aria-pressed={currentMonth===String(month)}>Mình tháng {month}! 🎂</button>)}</div><button type="button" className="modal-cancel" onClick={()=>setMonthOpen(false)}>Để sau</button></section></div>}
  {galleryOpen&&<div className="social-modal" role="dialog" aria-modal="true" aria-labelledby="gallery-title" onMouseDown={e=>{if(e.target===e.currentTarget)setGalleryOpen(false)}}><section className="gallery-picker"><header><div><small>THƯ VIỆN MÔ PHỎNG</small><h2 id="gallery-title">Chọn một khoảnh khắc</h2></div><button type="button" onClick={()=>setGalleryOpen(false)} aria-label="Đóng thư viện"><X/></button></header><p>Đây là các hình ảnh có sẵn trong Social Zone.</p><div className="gallery-grid">{galleryOptions.map(x=><button type="button" key={x.id} className={selected===x.id?"selected":""} onClick={()=>setSelected(x.id)} aria-pressed={selected===x.id}><div className={`gallery-scene gallery-${x.id}`} role="img" aria-label={x.alt}>{x.detail&&<span className="scene-detail" aria-hidden="true">{x.detail}</span>}<span className="scene-visual" aria-hidden="true">{x.visual}</span></div><strong>{x.title}</strong><small>{x.description}</small></button>)}</div><div className="gallery-actions"><button type="button" className="modal-cancel" onClick={()=>setGalleryOpen(false)}>Hủy</button><button type="button" className="publish-photo" disabled={!selected} onClick={publish}>Đăng khoảnh khắc</button></div></section></div>}
 </>;
}
